import type { Metadata } from "next";
import LegalPage, { LegalSection, OperatorFields } from "@/components/LegalPage";
export const metadata: Metadata = { title: "Datenschutz · 개인정보 | German Hanguk", robots: { index: false } };
export default function Page() {
  return <LegalPage title="Datenschutz" koreanTitle="개인정보 처리 안내">
    <section><h2 lang="de">Verantwortlicher und offene Betriebsangaben</h2><h3 lang="ko">책임자 및 미설정 운영 정보</h3><OperatorFields fields={["operatorName","serviceAddress","contactEmail","privacyContactAndDpo","competentPrivacyAuthority","hostingProviderAndLocation","supabaseContractRegionAndTransfers","otherRecipientsAndTransfers","contactLegalBasisAndInterests","retentionAndDeletionSchedule","otherSiteProcessingAndCookies"]} /></section>
    <LegalSection title="Kontaktformular: Daten und Zweck" koreanTitle="문의 양식: 수집 정보 및 목적" de="Wir speichern Kategorie, Betreff, optionalen Namen, E-Mail-Adresse, Nachricht, Eingangszeit, Bearbeitungsstatus und vorgesehenen Löschzeitpunkt, um die Anfrage zu bearbeiten und zu beantworten. E-Mail, Betreff, Nachricht und Kenntnisnahme dieses Hinweises sind erforderlich. Bitte keine sensiblen Daten oder fremden personenbezogenen Daten mitsenden." ko="문의 처리 및 답변을 위해 분류, 제목, 선택적 이름, 이메일, 메시지, 접수 시간, 처리 상태와 삭제 예정 시간을 저장합니다. 이메일, 제목, 메시지 및 안내 확인은 필수입니다. 민감한 정보나 다른 사람의 개인정보를 보내지 마세요." />
    <LegalSection title="Missbrauchsschutz und Zugriff" koreanTitle="남용 방지 및 접근" de="Für das Ratenlimit wird die normalisierte E-Mail-Adresse mit einem nur intern gespeicherten Zufallswert per SHA-256 gehasht. Das Formular speichert keine IP-Adresse, Gerätekennung oder Konto-ID. Ein unsichtbares Prüf-Feld wird nur auf Leerheit geprüft und nicht gespeichert. Pro E-Mail sind höchstens drei erfolgreiche Anfragen pro Stunde und zehn pro 24 Stunden vorgesehen; zusätzlich gilt eine globale Obergrenze von 100 Anfragen pro Stunde. Besucher haben keinen Lesezugriff auf gespeicherte Anfragen." ko="제출 빈도 제한을 위해 정규화된 이메일과 내부에만 저장되는 난수 값을 SHA-256으로 해시합니다. 양식은 IP 주소, 기기 식별자 또는 계정 ID를 저장하지 않습니다. 숨겨진 검사 필드는 비어 있는지만 확인하며 저장하지 않습니다. 이메일당 시간당 최대 3건, 24시간당 최대 10건이며 전체 문의는 시간당 100건으로 제한됩니다. 방문자는 저장된 문의를 읽을 수 없습니다." />
    <LegalSection title="Speicherung und Löschung" koreanTitle="보관 및 삭제" de="Technisch ist ein Löschzeitpunkt 90 Tage nach Eingang vorgesehen; Ratenlimit-Datensätze laufen nach einem Tag ab. Dies ist eine technische Voreinstellung, keine bestätigte rechtliche Aufbewahrungsfrist. Ein interner Löschlauf ist vorbereitet, aber noch nicht automatisch eingeplant. Der Betreiber muss Fristen, Backups und erforderliche Ausnahmen bestätigen und den regelmäßigen Löschlauf einrichten." ko="기술상 문의 삭제 예정 시점은 접수 후 90일이며 빈도 제한 기록은 하루 후 만료됩니다. 이는 법적으로 확인된 보관 기간이 아닌 기본 설정입니다. 내부 삭제 기능은 준비되었지만 자동 일정은 아직 설정되지 않았습니다. 운영자가 보관 기간, 백업 및 필요한 예외를 확인하고 정기 삭제를 설정해야 합니다." />
    <LegalSection title="Rechtsgrundlage und Ihre Rechte" koreanTitle="법적 근거 및 권리" de="Die konkrete Rechtsgrundlage ist durch den Betreiber zu bestätigen. Je nach Anfrage kommen insbesondere Art. 6 Abs. 1 lit. b oder lit. f DSGVO in Betracht. Die Checkbox bestätigt nur die Kenntnisnahme der Datenschutzhinweise. Nach den gesetzlichen Voraussetzungen bestehen insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde." ko="구체적인 법적 근거는 운영자가 확인해야 합니다. 문의 성격에 따라 특히 GDPR 제6조 제1항 b호 또는 f호가 적용될 수 있습니다. 체크박스는 개인정보 안내 확인일 뿐 광고 동의가 아닙니다. 법적 요건에 따라 열람, 정정, 삭제, 처리 제한, 데이터 이동, 이의 제기 및 개인정보 감독기관에 민원을 제기할 권리가 있습니다." />
    <p><a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj/deu">DSGVO / GDPR</a></p>
  </LegalPage>;
}

