import type { Metadata } from "next";
import LegalPage, { LegalSection, OperatorFields } from "@/components/LegalPage";
export const metadata: Metadata = { title: "Datenschutz · 개인정보 | German Hanguk", robots: { index: false } };
export default function Page() {
  return <LegalPage title="Datenschutz" koreanTitle="개인정보 처리 안내">
    <section><h2 lang="de">Verantwortlicher und Kontakt</h2><h3 lang="ko">개인정보 처리 책임자 및 연락처</h3><p lang="de">Datenschutzanfragen können an <a href="mailto:germanhanguk@gmail.com">germanhanguk@gmail.com</a> gerichtet werden.</p><p lang="ko">개인정보 관련 요청은 <a href="mailto:germanhanguk@gmail.com">germanhanguk@gmail.com</a>으로 보내 주세요.</p><OperatorFields fields={["operatorName", "serviceAddress", "privacyContactAndDpo", "competentPrivacyAuthority"]} /></section>
    <LegalSection title="Konten und Community" koreanTitle="계정 및 커뮤니티" de="Der Dienst verwendet Supabase für Authentifizierung und die Community-Datenbank. Im aktuellen Funktionsumfang sind E-Mail-/Passwort-Registrierung und -Login sowie Google-Login vorgesehen. Für Konten, Profile, Beiträge, Kommentare, Reaktionen, Benachrichtigungen, Direktnachrichten und Tandem-/Community-Funktionen werden jeweils die von Nutzern eingegebenen oder bei der Nutzung entstehenden Daten verarbeitet. Profilbilder und Bilder in Beiträgen werden in Supabase Storage gespeichert. Die konkrete Datenkategorie hängt von der verwendeten Funktion ab." ko="이 서비스는 인증과 커뮤니티 데이터베이스에 Supabase를 사용합니다. 현재 기능에는 이메일/비밀번호 가입·로그인 및 Google 로그인이 포함됩니다. 계정, 프로필, 게시물, 댓글, 반응, 알림, 쪽지 및 탠덤/커뮤니티 기능에서는 사용자가 입력하거나 이용 중 생성되는 데이터를 해당 기능 제공을 위해 처리합니다. 프로필 사진과 게시물 이미지는 Supabase Storage에 저장됩니다. 처리되는 구체적인 데이터 항목은 사용한 기능에 따라 달라집니다." />
    <LegalSection title="Kontaktformular" koreanTitle="문의 양식" de="Wir speichern Kategorie, Betreff, optionalen Namen, E-Mail-Adresse, Nachricht, Eingangszeit und Bearbeitungsstatus, um die Anfrage zu bearbeiten und zu beantworten. Das Formular nutzt ein leeres Prüf-Feld gegen automatisierte Einreichungen. Für die Begrenzung der Anfragen wird die normalisierte E-Mail-Adresse zusammen mit einem internen Zufallswert gehasht; das Formular selbst speichert keine IP-Adresse, Gerätekennung oder Konto-ID." ko="문의 처리와 답변을 위해 유형, 제목, 선택적 이름, 이메일, 메시지, 접수 시각 및 처리 상태를 저장합니다. 양식은 자동 제출 방지를 위해 비어 있어야 하는 검사 필드를 사용합니다. 제출 제한을 위해 정규화한 이메일 주소와 내부 난수를 결합해 해시하며, 양식 자체는 IP 주소, 기기 식별자 또는 계정 ID를 저장하지 않습니다." />
    <LegalSection title="Technische Speicherung und externe Inhalte" koreanTitle="기술적 저장 및 외부 콘텐츠" de="Der Quellcode speichert Sprache, Design-Einstellung und einzelne Nutzungsmarkierungen im lokalen oder Sitzungs-Speicher des Browsers. Er setzt keinen eigenen Analyse- oder Werbedienst ein. Eingebettete YouTube-, Instagram- und TikTok-Inhalte werden erst nach einem aktiven Klick geladen; dabei können die jeweiligen Anbieter Verbindungsdaten verarbeiten. Für die Auslieferung ist eine Vercel-Konfiguration im Projekt vorhanden. Standort, Vertragspartei, Protokolldaten, konkrete Supabase-Region und mögliche Drittlandübermittlungen sind im Projekt nicht verifiziert und müssen vom Betreiber vor einer abschließenden rechtlichen Prüfung ergänzt werden." ko="소스 코드는 언어, 테마 설정 및 일부 이용 표시를 브라우저의 로컬 또는 세션 저장소에 보관합니다. 자체 분석 또는 광고 서비스는 코드에서 확인되지 않습니다. YouTube·Instagram·TikTok 임베드는 사용자가 직접 불러오기를 누른 뒤에만 연결되며, 그때 각 제공자가 접속 정보를 처리할 수 있습니다. 프로젝트에는 Vercel 배포 설정이 있습니다. 호스팅 위치·계약 주체·로그 데이터, 구체적인 Supabase 리전 및 국외 이전 여부는 프로젝트에서 확인되지 않아 운영자가 최종 법률 검토 전에 보완해야 합니다." />
    <LegalSection title="Speicherung, Löschung und Rechte" koreanTitle="보관·삭제 및 이용자 권리" de="Für Kontaktanfragen ist technisch ein Löschzeitpunkt 90 Tage nach Eingang vorgesehen; Rate-Limit-Datensätze laufen nach einem Tag ab. Ein automatischer Löschlauf ist im Projekt vorbereitet, aber nicht als regelmäßiger Ablauf bestätigt. Für Konto- und Community-Daten ist keine abschließend geprüfte Aufbewahrungsfrist im Quellcode hinterlegt. Nach den gesetzlichen Voraussetzungen bestehen insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde." ko="문의는 기술상 접수 후 90일의 삭제 예정 시점이 설정되어 있고, 제출 제한 기록은 하루 후 만료됩니다. 자동 삭제 기능은 준비되어 있으나 정기 실행 여부는 확인되지 않았습니다. 계정 및 커뮤니티 데이터의 최종 보관 기간은 소스 코드에서 확정되어 있지 않습니다. 법적 요건에 따라 열람·정정·삭제·처리 제한·데이터 이동·이의 제기 및 개인정보 감독기관 민원 제기 권리가 있을 수 있습니다." />
    <p><a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj/deu">DSGVO / GDPR</a></p>
  </LegalPage>;
}
