-- Phase 8: community reputation, privacy controls, and Germany tenure.
-- Non-destructive migration. Apply only after reviewing against the live schema.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS germany_since date,
  ADD COLUMN IF NOT EXISTS show_community_level boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_germany_tenure boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_reputation_stats boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS reputation_xp integer NOT NULL DEFAULT 0 CHECK (reputation_xp >= 0),
  ADD COLUMN IF NOT EXISTS activity_score integer NOT NULL DEFAULT 0 CHECK (activity_score >= 0),
  ADD COLUMN IF NOT EXISTS knowledge_score integer NOT NULL DEFAULT 0 CHECK (knowledge_score >= 0),
  ADD COLUMN IF NOT EXISTS communication_score integer NOT NULL DEFAULT 0 CHECK (communication_score >= 0),
  ADD COLUMN IF NOT EXISTS helpful_score integer NOT NULL DEFAULT 0 CHECK (helpful_score >= 0);

COMMENT ON COLUMN public.profiles.germany_since IS '독일 생활 시작일. 원본 날짜는 공개 UI에 직접 노출하지 않음.';
COMMENT ON COLUMN public.profiles.show_community_level IS '게시글/댓글 및 공개 프로필에 커뮤니티 등급 표시 여부';
COMMENT ON COLUMN public.profiles.show_germany_tenure IS '계산된 독일생활 기간 표시 여부';
COMMENT ON COLUMN public.profiles.show_reputation_stats IS '공개 프로필에 활동/지식/소통/도움 수치 표시 여부';

CREATE TABLE IF NOT EXISTS public.reputation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  source_key text NOT NULL,
  xp_delta integer NOT NULL DEFAULT 0,
  activity_delta integer NOT NULL DEFAULT 0,
  knowledge_delta integer NOT NULL DEFAULT 0,
  communication_delta integer NOT NULL DEFAULT 0,
  helpful_delta integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reputation_events_source_unique UNIQUE (user_id, event_type, source_key)
);

CREATE INDEX IF NOT EXISTS idx_reputation_events_user_created
  ON public.reputation_events (user_id, created_at DESC);

ALTER TABLE public.reputation_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own reputation events" ON public.reputation_events;
CREATE POLICY "Users can read own reputation events"
  ON public.reputation_events FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Event ledger is DB-owned. Clients cannot insert/update/delete score events directly.
REVOKE INSERT, UPDATE, DELETE ON public.reputation_events FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.apply_reputation_event(
  p_user_id uuid,
  p_event_type text,
  p_source_key text,
  p_xp integer DEFAULT 0,
  p_activity integer DEFAULT 0,
  p_knowledge integer DEFAULT 0,
  p_communication integer DEFAULT 0,
  p_helpful integer DEFAULT 0
) RETURNS boolean AS $$
DECLARE
  v_inserted_count integer := 0;
BEGIN
  INSERT INTO public.reputation_events (
    user_id, event_type, source_key, xp_delta, activity_delta,
    knowledge_delta, communication_delta, helpful_delta
  ) VALUES (
    p_user_id, p_event_type, p_source_key, p_xp, p_activity,
    p_knowledge, p_communication, p_helpful
  ) ON CONFLICT (user_id, event_type, source_key) DO NOTHING;

  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

  IF v_inserted_count > 0 THEN
    UPDATE public.profiles
    SET reputation_xp = GREATEST(0, reputation_xp + p_xp),
        activity_score = GREATEST(0, activity_score + p_activity),
        knowledge_score = GREATEST(0, knowledge_score + p_knowledge),
        communication_score = GREATEST(0, communication_score + p_communication),
        helpful_score = GREATEST(0, helpful_score + p_helpful),
        updated_at = now()
    WHERE id = p_user_id;
  END IF;
  RETURN v_inserted_count > 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

REVOKE ALL ON FUNCTION public.apply_reputation_event(uuid,text,text,integer,integer,integer,integer,integer) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.handle_post_reputation()
RETURNS trigger AS $$
BEGIN
  IF NEW.author_id IS NOT NULL THEN
    PERFORM public.apply_reputation_event(NEW.author_id, 'POST_CREATED', NEW.id::text, 3, 3, 0, 0, 0);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

DROP TRIGGER IF EXISTS trg_post_reputation ON public.posts;
CREATE TRIGGER trg_post_reputation AFTER INSERT ON public.posts
FOR EACH ROW EXECUTE FUNCTION public.handle_post_reputation();

CREATE OR REPLACE FUNCTION public.handle_comment_reputation()
RETURNS trigger AS $$
BEGIN
  IF NEW.author_id IS NOT NULL THEN
    PERFORM public.apply_reputation_event(NEW.author_id, 'COMMENT_CREATED', NEW.id::text, 1, 1, 0, 1, 0);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

DROP TRIGGER IF EXISTS trg_comment_reputation ON public.comments;
CREATE TRIGGER trg_comment_reputation AFTER INSERT ON public.comments
FOR EACH ROW EXECUTE FUNCTION public.handle_comment_reputation();

CREATE OR REPLACE FUNCTION public.handle_received_like_reputation()
RETURNS trigger AS $$
DECLARE
  v_author_id uuid;
BEGIN
  SELECT author_id INTO v_author_id FROM public.posts WHERE id = NEW.post_id;
  IF v_author_id IS NOT NULL AND v_author_id <> NEW.user_id THEN
    PERFORM public.apply_reputation_event(v_author_id, 'POST_LIKE_RECEIVED', NEW.id::text, 1, 0, 0, 0, 1);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

DROP TRIGGER IF EXISTS trg_received_like_reputation ON public.post_likes;
CREATE TRIGGER trg_received_like_reputation AFTER INSERT ON public.post_likes
FOR EACH ROW EXECUTE FUNCTION public.handle_received_like_reputation();

CREATE TABLE IF NOT EXISTS public.guide_read_rewards (
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  guide_slug text NOT NULL,
  rewarded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, guide_slug)
);

ALTER TABLE public.guide_read_rewards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own guide rewards" ON public.guide_read_rewards;
CREATE POLICY "Users can read own guide rewards" ON public.guide_read_rewards
FOR SELECT TO authenticated USING (auth.uid() = user_id);
REVOKE INSERT, UPDATE, DELETE ON public.guide_read_rewards FROM anon, authenticated;

-- Guide rewards are intentionally exposed only through this authenticated RPC.
-- The UI should call it only after a meaningful read signal, never on page load.
CREATE OR REPLACE FUNCTION public.reward_guide_read(p_guide_slug text)
RETURNS boolean AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_inserted_count integer := 0;
BEGIN
  IF v_user_id IS NULL OR nullif(trim(p_guide_slug), '') IS NULL THEN RETURN false; END IF;

  INSERT INTO public.guide_read_rewards (user_id, guide_slug)
  VALUES (v_user_id, trim(p_guide_slug))
  ON CONFLICT (user_id, guide_slug) DO NOTHING;
  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

  IF v_inserted_count > 0 THEN
    PERFORM public.apply_reputation_event(v_user_id, 'GUIDE_FIRST_READ', trim(p_guide_slug), 1, 0, 1, 0, 0);
    RETURN true;
  END IF;
  RETURN false;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

REVOKE ALL ON FUNCTION public.reward_guide_read(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reward_guide_read(text) TO authenticated;

-- germany_since is intentionally not exposed through a public view; clients show only a calculated tenure label.
-- Existing users start at zero. We do not retroactively award points because historical rows may include imports/tests.

