-- Phase 8: community reputation, privacy controls, and Germany tenure.
-- Non-destructive migration. Apply only after reviewing against the live schema.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS show_community_level boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_germany_tenure boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_reputation_stats boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS public.profile_private_details (
  user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  germany_since date,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.profile_private_details ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own private profile details" ON public.profile_private_details
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.community_reputation (
  user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  reputation_xp integer NOT NULL DEFAULT 0 CHECK (reputation_xp >= 0),
  activity_score integer NOT NULL DEFAULT 0 CHECK (activity_score >= 0),
  knowledge_score integer NOT NULL DEFAULT 0 CHECK (knowledge_score >= 0),
  communication_score integer NOT NULL DEFAULT 0 CHECK (communication_score >= 0),
  helpful_score integer NOT NULL DEFAULT 0 CHECK (helpful_score >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.community_reputation ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own reputation totals" ON public.community_reputation
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
REVOKE INSERT, UPDATE, DELETE ON public.community_reputation FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public.reputation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  source_key text NOT NULL,
  xp_delta integer NOT NULL DEFAULT 0,
  activity_delta integer NOT NULL DEFAULT 0,
  knowledge_delta integer NOT NULL DEFAULT 0,
  communication_delta integer NOT NULL DEFAULT 0,
  helpful_delta integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reputation_events_source_unique UNIQUE (user_id, event_type, source_key)
);

CREATE INDEX IF NOT EXISTS idx_reputation_events_user_created
  ON public.reputation_events (user_id, created_at DESC);

ALTER TABLE public.reputation_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own reputation events" ON public.reputation_events;
CREATE POLICY "Users can read own reputation events"
  ON public.reputation_events FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Event ledger is DB-owned. Clients cannot insert/update/delete score events directly.
REVOKE INSERT, UPDATE, DELETE ON public.reputation_events FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.apply_reputation_event(
  p_user_id uuid,
  p_event_type text,
  p_source_key text,
  p_xp integer DEFAULT 0,
  p_activity integer DEFAULT 0,
  p_knowledge integer DEFAULT 0,
  p_communication integer DEFAULT 0,
  p_helpful integer DEFAULT 0
) RETURNS boolean AS $$
DECLARE
  v_inserted_count integer := 0;
  v_daily_count integer := 0;
  v_daily_limit integer := CASE p_event_type
    WHEN 'POST_CREATED' THEN 5
    WHEN 'COMMENT_CREATED' THEN 20
    WHEN 'POST_LIKE_RECEIVED' THEN 30
    WHEN 'GUIDE_FIRST_READ' THEN 10
    ELSE NULL
  END;
BEGIN
  IF v_daily_limit IS NOT NULL THEN
    SELECT count(*) INTO v_daily_count
    FROM public.reputation_events
    WHERE user_id = p_user_id
      AND event_type = p_event_type
      AND created_at >= date_trunc('day', now());
    IF v_daily_count >= v_daily_limit THEN RETURN false; END IF;
  END IF;

  INSERT INTO public.reputation_events (
    user_id, event_type, source_key, xp_delta, activity_delta,
    knowledge_delta, communication_delta, helpful_delta
  ) VALUES (
    p_user_id, p_event_type, p_source_key, p_xp, p_activity,
    p_knowledge, p_communication, p_helpful
  ) ON CONFLICT (user_id, event_type, source_key) DO NOTHING;

  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

  IF v_inserted_count > 0 THEN
    INSERT INTO public.community_reputation (
      user_id, reputation_xp, activity_score, knowledge_score, communication_score, helpful_score
    ) VALUES (p_user_id, GREATEST(0, p_xp), GREATEST(0, p_activity), GREATEST(0, p_knowledge), GREATEST(0, p_communication), GREATEST(0, p_helpful))
    ON CONFLICT (user_id) DO UPDATE SET
      reputation_xp = GREATEST(0, public.community_reputation.reputation_xp + p_xp),
      activity_score = GREATEST(0, public.community_reputation.activity_score + p_activity),
      knowledge_score = GREATEST(0, public.community_reputation.knowledge_score + p_knowledge),
      communication_score = GREATEST(0, public.community_reputation.communication_score + p_communication),
      helpful_score = GREATEST(0, public.community_reputation.helpful_score + p_helpful),
      updated_at = now();
  END IF;
  RETURN v_inserted_count > 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

REVOKE ALL ON FUNCTION public.apply_reputation_event(uuid,text,text,integer,integer,integer,integer,integer) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.handle_post_reputation()
RETURNS trigger AS $$
BEGIN
  IF NEW.author_id IS NOT NULL THEN
    PERFORM public.apply_reputation_event(NEW.author_id, 'POST_CREATED', NEW.id::text, 3, 3, 0, 0, 0);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

DROP TRIGGER IF EXISTS trg_post_reputation ON public.posts;
CREATE TRIGGER trg_post_reputation AFTER INSERT ON public.posts
FOR EACH ROW EXECUTE FUNCTION public.handle_post_reputation();

CREATE OR REPLACE FUNCTION public.handle_comment_reputation()
RETURNS trigger AS $$
BEGIN
  IF NEW.author_id IS NOT NULL THEN
    PERFORM public.apply_reputation_event(NEW.author_id, 'COMMENT_CREATED', NEW.id::text, 1, 1, 0, 1, 0);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

DROP TRIGGER IF EXISTS trg_comment_reputation ON public.comments;
CREATE TRIGGER trg_comment_reputation AFTER INSERT ON public.comments
FOR EACH ROW EXECUTE FUNCTION public.handle_comment_reputation();

CREATE OR REPLACE FUNCTION public.handle_received_like_reputation()
RETURNS trigger AS $$
DECLARE
  v_author_id uuid;
BEGIN
  SELECT author_id INTO v_author_id FROM public.posts WHERE id = NEW.post_id;
  IF v_author_id IS NOT NULL AND v_author_id <> NEW.user_id THEN
    PERFORM public.apply_reputation_event(v_author_id, 'POST_LIKE_RECEIVED', NEW.post_id::text || ':' || NEW.user_id::text, 1, 0, 0, 0, 1);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

DROP TRIGGER IF EXISTS trg_received_like_reputation ON public.post_likes;
CREATE TRIGGER trg_received_like_reputation AFTER INSERT ON public.post_likes
FOR EACH ROW EXECUTE FUNCTION public.handle_received_like_reputation();

CREATE TABLE IF NOT EXISTS public.guide_read_rewards (
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  guide_slug text NOT NULL,
  rewarded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, guide_slug)
);

ALTER TABLE public.guide_read_rewards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own guide rewards" ON public.guide_read_rewards;
CREATE POLICY "Users can read own guide rewards" ON public.guide_read_rewards
FOR SELECT TO authenticated USING (auth.uid() = user_id);
REVOKE INSERT, UPDATE, DELETE ON public.guide_read_rewards FROM anon, authenticated;

-- Guide rewards are intentionally exposed only through this authenticated RPC.
-- The UI should call it only after a meaningful read signal, never on page load.
CREATE OR REPLACE FUNCTION public.reward_guide_read(p_guide_slug text)
RETURNS boolean AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_inserted_count integer := 0;
BEGIN
  IF v_user_id IS NULL OR nullif(trim(p_guide_slug), '') IS NULL THEN RETURN false; END IF;

  INSERT INTO public.guide_read_rewards (user_id, guide_slug)
  VALUES (v_user_id, trim(p_guide_slug))
  ON CONFLICT (user_id, guide_slug) DO NOTHING;
  GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

  IF v_inserted_count > 0 THEN
    PERFORM public.apply_reputation_event(v_user_id, 'GUIDE_FIRST_READ', trim(p_guide_slug), 1, 0, 1, 0, 0);
    RETURN true;
  END IF;
  RETURN false;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

REVOKE ALL ON FUNCTION public.reward_guide_read(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reward_guide_read(text) TO authenticated;

CREATE OR REPLACE FUNCTION public.get_public_community_identity(p_user_id uuid)
RETURNS TABLE (
  reputation_xp integer, tenure_value integer, tenure_unit text,
  activity_score integer, knowledge_score integer, communication_score integer, helpful_score integer,
  show_community_level boolean, show_germany_tenure boolean, show_reputation_stats boolean
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    CASE WHEN p.show_community_level THEN COALESCE(r.reputation_xp, 0) ELSE NULL END,
    CASE WHEN p.show_germany_tenure AND d.germany_since IS NOT NULL AND d.germany_since <= current_date THEN
      CASE WHEN current_date - d.germany_since < 31 THEN current_date - d.germany_since + 1
           WHEN EXTRACT(YEAR FROM age(current_date, d.germany_since)) < 1 THEN GREATEST(1, EXTRACT(MONTH FROM age(current_date, d.germany_since))::integer)
           ELSE EXTRACT(YEAR FROM age(current_date, d.germany_since))::integer END ELSE NULL END,
    CASE WHEN p.show_germany_tenure AND d.germany_since IS NOT NULL AND d.germany_since <= current_date THEN
      CASE WHEN current_date - d.germany_since < 31 THEN 'day'
           WHEN EXTRACT(YEAR FROM age(current_date, d.germany_since)) < 1 THEN 'month' ELSE 'year' END ELSE NULL END,
    CASE WHEN p.show_reputation_stats THEN COALESCE(r.activity_score, 0) ELSE NULL END,
    CASE WHEN p.show_reputation_stats THEN COALESCE(r.knowledge_score, 0) ELSE NULL END,
    CASE WHEN p.show_reputation_stats THEN COALESCE(r.communication_score, 0) ELSE NULL END,
    CASE WHEN p.show_reputation_stats THEN COALESCE(r.helpful_score, 0) ELSE NULL END,
    p.show_community_level, p.show_germany_tenure, p.show_reputation_stats
  FROM public.profiles p
  LEFT JOIN public.profile_private_details d ON d.user_id = p.id
  LEFT JOIN public.community_reputation r ON r.user_id = p.id
  WHERE p.id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';
REVOKE ALL ON FUNCTION public.get_public_community_identity(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_public_community_identity(uuid) TO anon, authenticated;

-- Exact Germany start dates and hidden score totals remain behind RLS; public clients receive privacy-filtered RPC output only.
-- Existing users start at zero. Historical posts/comments are not backfilled.

-- Batch form used by community lists/comments to avoid one RPC per author.
CREATE OR REPLACE FUNCTION public.get_public_community_identities(p_user_ids uuid[])
RETURNS TABLE (
  user_id uuid, reputation_xp integer, tenure_value integer, tenure_unit text,
  show_community_level boolean, show_germany_tenure boolean
) AS $$
  SELECT p.id,
    CASE WHEN p.show_community_level THEN COALESCE(r.reputation_xp, 0) ELSE NULL END,
    CASE WHEN p.show_germany_tenure AND d.germany_since IS NOT NULL AND d.germany_since <= current_date THEN
      CASE WHEN current_date - d.germany_since < 31 THEN current_date - d.germany_since + 1
           WHEN EXTRACT(YEAR FROM age(current_date, d.germany_since)) < 1 THEN GREATEST(1, EXTRACT(MONTH FROM age(current_date, d.germany_since))::integer)
           ELSE EXTRACT(YEAR FROM age(current_date, d.germany_since))::integer END ELSE NULL END,
    CASE WHEN p.show_germany_tenure AND d.germany_since IS NOT NULL AND d.germany_since <= current_date THEN
      CASE WHEN current_date - d.germany_since < 31 THEN 'day'
           WHEN EXTRACT(YEAR FROM age(current_date, d.germany_since)) < 1 THEN 'month' ELSE 'year' END ELSE NULL END,
    p.show_community_level, p.show_germany_tenure
  FROM public.profiles p
  LEFT JOIN public.profile_private_details d ON d.user_id = p.id
  LEFT JOIN public.community_reputation r ON r.user_id = p.id
  WHERE p.id = ANY(p_user_ids);
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '';
REVOKE ALL ON FUNCTION public.get_public_community_identities(uuid[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_public_community_identities(uuid[]) TO anon, authenticated;
