BEGIN;

CREATE TABLE IF NOT EXISTS public.article_automation_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_key text NOT NULL UNIQUE,
  local_date date NOT NULL,
  local_hour smallint NOT NULL CHECK (local_hour IN (8, 19)),
  state text NOT NULL DEFAULT 'running' CHECK (state IN ('running','success','failed')),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  article_id uuid REFERENCES public.articles(id) ON DELETE SET NULL,
  result_reason text,
  error_message text CHECK (error_message IS NULL OR char_length(error_message) <= 500)
);

ALTER TABLE public.article_automation_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.article_automation_runs FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.article_automation_runs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.article_automation_runs_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS article_automation_runs_started_at_idx
  ON public.article_automation_runs(started_at DESC);

COMMIT;
